# Generated by Django 3.1 on 2020-10-02 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0021_auto_20201001_0441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='exp_date',
            field=models.DateField(default='2020-11-01'),
        ),
    ]
